# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298583522c612cc5742db9efd09dce9f6375daf79f661e6fbde6494ff87e82857526fc8169897f2bfa2320519aa5b18e899320a7d67d24d66d285fe0f24b7bfb

test:
  secret_key_base: 7ff39c8d9078a062e0dad7931421323e3e90d02015e7ecdedfb9d0b4374ccb99d5fa96ed9727d592ad93ecaadc7999f3042053bb8516b3c12be2161b28703ccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
